### ISSUE TITLE
📆🖱 Calendar JS: drag and drop events to change their dates

### ISSUE THREAD

**Issue by mghilea** [jamesdaus/COSC415-ToDo#59]

**Comment by lilyosah** [comment]
Dragula: https://github.com/bevacqua/dragula
Using third-party drag and drop: https://fullcalendar.io/docs/third-party-dragging

**Comment by lilyosah** [comment]
External to internal dragging and dropping https://fullcalendar.io/docs/external-dragging

**Comment by lilyosah** [comment]
To help with cross-list dropping: https://fullcalendar.io/docs/eventDataTransform
